### PR TITLE
chore: bump `blockifier` to `v0.16.0-rc.0`

### PR DESCRIPTION
**Pull request by kariy**
Related #393, #388, #198, #209, #211, #256, #268.

When running `cargo vendor`, we're stuck with this error:

```
λ cargo vendor
error: failed to sync

Caused by:
  found duplicate version of package `starknet-crypto v0.7.4` vendored from two sources:

  	source 1: registry `crates-io`
  	source 2: https://github.com/kariy/starknet-rs?rev=2ef3088#2ef30887
```

The dependencies bump is required because we are removing the `starknet` crate patch:

```toml
[patch.crates-io]
starknet = { git = "https://github.com/kariy/starknet-rs", rev = "2ef3088" }
```

The initial reason for the patch is for this PR https://github.com/xJonathanLEI/starknet-rs/pull/773 but it's no longer needed since #256.

The dependency updates were originally meant to only make the project compile after removing the patch. Given the tight integration with `blockifier` and the breaking database format change introduced in `v0.16.0-rc.0`, this PR is now primarily about updating `blockifier`, with patch removal as a side effect.

### TransactionExecutionInfo

`blockifier` v0.16.0-rc.0 has a breaking change in the `TransactionExecutionInfo` struct. In order to maintain backward-compatibility, if database can't deserialize the `TransactionExecutionInfo` it'd simply return nothing instead of failing.

This is still temporary for now and may change once we find a better solution that doesn't require dropping old data.

### Felt Serialization

The `starknet-types-core` crate has a breaking change in `Felt` serialization (see https://github.com/starknet-io/types-rs/pull/155). To maintain backward compatibility with existing databases, a `Felt32` wrapper type is used to ensure `Felt` values are always serialized as 32-byte big-endian arrays when stored in the database.

---

The reason to vendor the Cargo dependencies is to make the Katana binary build hermetic in order to achieve reproducible build process.

### CODE REVIEW

**Comment by kariy** [comment]
at commit [`7863d73`](https://github.com/dojoengine/katana/pull/392/commits/7863d73ff7d14b401bc5bf86afc16177af6544b8), compiling the project will fail with:

```
error[E0433]: failed to resolve: could not find `__private` in `serde`
   --> /Users/kariy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-consensus-1.0.24/src/transaction/envelope.rs:162:24
    |
162 | #[derive(Clone, Debug, TransactionEnvelope)]
    |                        ^^^^^^^^^^^^^^^^^^^ could not find `__private` in `serde`
    |
    = note: this error originates in the derive macro `TransactionEnvelope` (in Nightly builds, run with -Z macro-backtrace for more info)
```

serde broke the private api in https://github.com/serde-rs/serde/pull/2980. solved in [`c0d1040`](https://github.com/dojoengine/katana/pull/392/commits/c0d10402952a3a92e5f77c2adfd0869a4b50c15d)

**Comment by kariy** [comment]
https://github.com/starknet-io/types-rs/pull/155 breaks the serialization format for `Felt` where the serialized array length is no longer assumed to always be **32**. [`61ad600`](https://github.com/dojoengine/katana/pull/392/commits/61ad600cda71463db660b4e0c9de3e96b9438e7d) fixes this to maintain backward compatibility
